version: "3.8"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p455w0rd
      POSTGRES_DB: team-roles

volumes:
  postgres:
